In [1]:
# ===== Task 19: Filter Dataset Records (Pandas) =====
import pandas as pd
import numpy as np
from IPython.display import display

# ---------- 1. Create and load the dataset ----------
rng = np.random.default_rng(7)
n = 50
hours  = np.clip(rng.normal(5, 2, n), 0.5, 10).round(1)
attend = np.clip(rng.normal(85, 8, n), 55, 100).round(0).astype(int)
prev   = np.clip(rng.normal(65, 12, n), 25, 100).round(0).astype(int)
final  = np.clip(0.35*prev + 4*hours + 0.25*attend + rng.normal(0, 5, n), 0, 100).round(0).astype(int)

df = pd.DataFrame({
    'student_id': np.arange(1, n+1),
    'gender': rng.choice(['Male', 'Female'], n),
    'hours_studied': hours,
    'attendance_pct': attend,
    'previous_score': prev,
    'final_score': final})
df['result'] = np.where(df['final_score'] >= 50, 'Pass', 'Fail')

df.to_csv('student_performance.csv', index=False)
df = pd.read_csv('student_performance.csv')
print('Total records:', len(df))
display(df.head())

def show(title, explanation, result):
    print('\n' + '=' * 70)
    print(title)
    print('Explanation:', explanation)
    print('Records found:', len(result))
    display(result)

# ---------- 2. Filtering examples ----------
high_scorers = df[df['final_score'] > 70]
show('Example 1: Single condition  ->  final_score > 70',
     'Keeps only students who scored above 70.', high_scorers)

failed = df[df['result'] == 'Fail']
show("Example 2: Text condition  ->  result == 'Fail'",
     'Keeps only students whose result is Fail.', failed)

dedicated = df[(df['gender'] == 'Female') & (df['hours_studied'] >= 5) & (df['attendance_pct'] > 85)]
show('Example 3: AND (&)  ->  Female, hours >= 5, attendance > 85',
     'A row is kept only if ALL conditions are true (strict).', dedicated)

either = df[(df['final_score'] > 60) | (df['hours_studied'] > 6)]
show('Example 4: OR (|)  ->  final_score > 60 OR hours_studied > 6',
     'A row is kept if AT LEAST ONE condition is true (broader).', either)

not_passed = df[~(df['result'] == 'Pass')]
show("Example 5: NOT (~)  ->  not (result == 'Pass')",
     'The ~ symbol reverses the condition.', not_passed)

selected = df[df['student_id'].isin([1, 5, 10, 15, 20])]
show('Example 6: isin()  ->  student_id in [1, 5, 10, 15, 20]',
     'Keeps rows whose value matches any value in the list.', selected)

mid_range = df[df['final_score'].between(55, 65)]
show('Example 7: between()  ->  final_score between 55 and 65',
     'Keeps rows whose value lies in the range (both ends included).', mid_range)

q = df.query('final_score > 65 and attendance_pct >= 85')
show('Example 8: query()  ->  final_score > 65 and attendance_pct >= 85',
     'Same as Boolean filtering, written as a string.', q)

show('Example 9: loc  ->  filter rows AND choose columns',
     'Filters final_score > 70 and shows only 3 columns.',
     df.loc[df['final_score'] > 70, ['student_id', 'hours_studied', 'final_score']])

# ---------- 3. Why parentheses matter ----------
print('\n' + '=' * 70)
print('Why parentheses matter')
try:
    df[df['final_score'] > 70 & df['gender'] == 'Male']
except Exception as e:
    print('Without parentheses -> error:', type(e).__name__)
right = df[(df['final_score'] > 70) & (df['gender'] == 'Male')]
print('With parentheses -> records found:', len(right))

# ---------- 4. Number of records after each filter ----------
print('\n' + '=' * 70)
counts = {
    'All records': len(df),
    'final_score > 70': len(high_scorers),
    "result == 'Fail'": len(failed),
    'Female & hours>=5 & attendance>85': len(dedicated),
    'final_score > 60 OR hours > 6': len(either),
    'final_score between 55 and 65': len(mid_range),
}
display(pd.Series(counts, name='records'))

# ---------- 5. Observations ----------
print('OBSERVATIONS')
print('-' * 50)
print(f'1. {len(high_scorers)} of {len(df)} students scored above 70 ({len(high_scorers)/len(df)*100:.0f}%).')
print(f'2. {len(failed)} students failed.')
print(f'3. OR is broader than AND: {len(either)} records matched at least one OR condition, while only {len(dedicated)} matched all three AND conditions.')

Total records: 50

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
0,1,Male,5.0,91,61,61,Pass
1,2,Male,5.6,75,54,58,Pass
2,3,Female,4.5,86,67,60,Pass
3,4,Female,3.2,90,92,68,Pass
4,5,Male,4.1,83,55,55,Pass

======================================================================
Example 1: Single condition  ->  final_score > 70
Explanation: Keeps only students who scored above 70.
Records found: 8

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
7,8,Female,7.7,90,71,74,Pass
8,9,Male,4.0,97,63,71,Pass
29,30,Female,5.2,97,74,71,Pass
34,35,Female,7.1,83,80,76,Pass
37,38,Male,6.8,81,62,73,Pass
44,45,Female,7.7,85,57,75,Pass
46,47,Male,6.7,75,80,78,Pass
49,50,Female,9.0,69,65,84,Pass

======================================================================
Example 2: Text condition  ->  result == 'Fail'
Explanation: Keeps only students whose result is Fail.
Records found: 5

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
13,14,Male,3.1,76,64,47,Fail
16,17,Female,2.3,92,68,47,Fail
20,21,Male,1.3,90,66,47,Fail
26,27,Female,0.5,82,39,43,Fail
30,31,Male,1.9,82,55,45,Fail

======================================================================
Example 3: AND (&)  ->  Female, hours >= 5, attendance > 85
Explanation: A row is kept only if ALL conditions are true (strict).
Records found: 6

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
7,8,Female,7.7,90,71,74,Pass
10,11,Female,6.0,87,73,66,Pass
29,30,Female,5.2,97,74,71,Pass
41,42,Female,5.1,90,58,68,Pass
43,44,Female,5.2,93,55,63,Pass
47,48,Female,5.2,88,63,69,Pass

======================================================================
Example 4: OR (|)  ->  final_score > 60 OR hours_studied > 6
Explanation: A row is kept if AT LEAST ONE condition is true (broader).
Records found: 24

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
0,1,Male,5.0,91,61,61,Pass
3,4,Female,3.2,90,92,68,Pass
7,8,Female,7.7,90,71,74,Pass
8,9,Male,4.0,97,63,71,Pass
10,11,Female,6.0,87,73,66,Pass
11,12,Female,5.7,81,71,70,Pass
12,13,Male,5.2,86,53,68,Pass
14,15,Female,4.9,80,65,61,Pass
15,16,Male,6.4,83,52,61,Pass
17,18,Male,4.1,94,55,63,Pass
29,30,Female,5.2,97,74,71,Pass
32,33,Female,3.0,88,67,61,Pass
34,35,Female,7.1,83,80,76,Pass
35,36,Female,3.4,76,82,61,Pass
36,37,Male,4.9,85,64,69,Pass
37,38,Male,6.8,81,62,73,Pass
38,39,Female,3.8,94,63,63,Pass
40,41,Male,5.2,85,78,62,Pass
41,42,Female,5.1,90,58,68,Pass
43,44,Female,5.2,93,55,63,Pass
44,45,Female,7.7,85,57,75,Pass
46,47,Male,6.7,75,80,78,Pass
47,48,Female,5.2,88,63,69,Pass
49,50,Female,9.0,69,65,84,Pass

======================================================================
Example 5: NOT (~)  ->  not (result == 'Pass')
Explanation: The ~ symbol reverses the condition.
Records found: 5

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
13,14,Male,3.1,76,64,47,Fail
16,17,Female,2.3,92,68,47,Fail
20,21,Male,1.3,90,66,47,Fail
26,27,Female,0.5,82,39,43,Fail
30,31,Male,1.9,82,55,45,Fail

======================================================================
Example 6: isin()  ->  student_id in [1, 5, 10, 15, 20]
Explanation: Keeps rows whose value matches any value in the list.
Records found: 5

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
0,1,Male,5.0,91,61,61,Pass
4,5,Male,4.1,83,55,55,Pass
9,10,Female,3.8,80,63,54,Pass
14,15,Female,4.9,80,65,61,Pass
19,20,Male,2.4,79,67,53,Pass

======================================================================
Example 7: between()  ->  final_score between 55 and 65
Explanation: Keeps rows whose value lies in the range (both ends included).
Records found: 23

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
0,1,Male,5.0,91,61,61,Pass
1,2,Male,5.6,75,54,58,Pass
2,3,Female,4.5,86,67,60,Pass
4,5,Male,4.1,83,55,55,Pass
6,7,Male,5.1,84,67,58,Pass
14,15,Female,4.9,80,65,61,Pass
15,16,Male,6.4,83,52,61,Pass
17,18,Male,4.1,94,55,63,Pass
21,22,Female,4.5,69,58,58,Pass
23,24,Female,5.5,84,41,57,Pass
24,25,Male,5.3,95,51,57,Pass
25,26,Male,4.6,91,69,59,Pass
27,28,Female,3.9,82,75,60,Pass
28,29,Male,4.9,83,44,57,Pass
31,32,Male,4.0,83,74,60,Pass
32,33,Female,3.0,88,67,61,Pass
35,36,Female,3.4,76,82,61,Pass
38,39,Female,3.8,94,63,63,Pass
39,40,Female,4.8,90,53,57,Pass
40,41,Male,5.2,85,78,62,Pass
42,43,Male,2.5,82,64,58,Pass
43,44,Female,5.2,93,55,63,Pass
48,49,Male,3.7,71,77,57,Pass

======================================================================
Example 8: query()  ->  final_score > 65 and attendance_pct >= 85
Explanation: Same as Boolean filtering, written as a string.
Records found: 10

,student_id,gender,hours_studied,attendance_pct,previous_score,final_score,result
3,4,Female,3.2,90,92,68,Pass
7,8,Female,7.7,90,71,74,Pass
8,9,Male,4.0,97,63,71,Pass
10,11,Female,6.0,87,73,66,Pass
12,13,Male,5.2,86,53,68,Pass
29,30,Female,5.2,97,74,71,Pass
36,37,Male,4.9,85,64,69,Pass
41,42,Female,5.1,90,58,68,Pass
44,45,Female,7.7,85,57,75,Pass
47,48,Female,5.2,88,63,69,Pass

======================================================================
Example 9: loc  ->  filter rows AND choose columns
Explanation: Filters final_score > 70 and shows only 3 columns.
Records found: 8

    student_id  hours_studied  final_score
7            8            7.7           74
8            9            4.0           71
29          30            5.2           71
34          35            7.1           76
37          38            6.8           73
44          45            7.7           75
46          47            6.7           78
49          50            9.0           84

======================================================================
Why parentheses matter
Without parentheses -> error: TypeError
With parentheses -> records found: 3

======================================================================

All records                          50
final_score > 70                      8
result == 'Fail'                      5
Female & hours>=5 & attendance>85     6
final_score > 60 OR hours > 6        24
final_score between 55 and 65        23
Name: records, dtype: int64

OBSERVATIONS
--------------------------------------------------
1. 8 of 50 students scored above 70 (16%).
2. 5 students failed.
3. OR is broader than AND: 24 records matched at least one OR condition, while only 6 matched all three AND conditions.

In [2]:
import os
print(os.getcwd())

C:\Users\AMULYA TOBACO\Desktop\Filter_dataset